Failure in inline-check.py:

  The CHECK on line 12 wants:
    match

  which failed to match line stdout:2:
    mismatch

  Context:
    ok
    mismatch <= does not match CHECK on line 12: match

  when running command:
    /bin/sh inline-check.py
