Failure in python_missing_output.py:

  The CHECK on line 8 wants:
    NotPrinted

  which failed to match line stdout:2:
    Second

  Context:
    First
     <= nothing to match CHECK on line 8: NotPrinted
    Second
    Third
    1
    [...] from line 24 (stdout:8):
    5
    6
    6
    foobar <= no check matches this, previous check on line 28
    barbar
    6
    6
    [...] from line 39 (stdout:16):
    6
    6
    6
    Fourth <= no more checks

  when running command:
    /usr/bin/python python_missing_output.py
