Failure in python_doublereplace.py:

  The CHECK on line 14 wants:
    0

  which failed to match line stdout:3:
    2

  Context:
    Checking that --quiet quits early - if this is broken it hangs
    0
    2 <= no check matches this, previous check on line 12
    0
    0
     <= nothing to match CHECK on line 19: 0

  when running command:
    /usr/bin/python3 python_doublereplace.py
